name: manutencao_carros
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.5.0 
  get_it: ^8.0.3 
  go_router: ^14.6.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2 
  build_runner: ^2.4.14  
  freezed: ^2.5.7
  json_serializable: ^6.9.0  

flutter:
  uses-material-design: true
